# GET http://localhost:5253

GET http://localhost:5253/games

###
GET http://localhost:5253/games/6

###
POST http://localhost:5253/games
Content-Type: application/json

{
    "name": "Black Myth Wukong",
    "genre": "Action RPG",
    "price": 59.99,
    "releaseDate": "2024-11-18"
}


###
PUT http://localhost:5253/games/6
Content-Type: application/json

{
    "name": "Black Myth Wukong",
    "genre": "Action RPG",
    "price": 159.99,
    "releaseDate": "2024-11-18"
}

###
DELETE http://localhost:5253/games/3