# GET http://localhost:5253

GET http://localhost:5253/games

###
GET http://localhost:5253/games/2

###
POST http://localhost:5253/games
Content-Type: application/json

{
    "name": "Black Myth Wukong",
    "genreId": 1,
    "price": 59.99,
    "releaseDate": "2024-11-18"
}


###
PUT http://localhost:5253/games/2
Content-Type: application/json

{
    "name": "Black Myth Bong",
    "genreId": "1",
    "price": 2.99,
    "releaseDate": "2024-11-18"
}

###
DELETE http://localhost:5253/games/2